# Generated by Django 3.1.3 on 2021-02-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
